# Generated by Django 2.2.3 on 2019-08-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20190812_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True, unique=True, verbose_name='文章标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, unique=True, verbose_name='创建时间')),
                ('category', models.ManyToManyField(null=True, to='app01.Blog', verbose_name='博客分类')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
            },
        ),
        migrations.AddField(
            model_name='articledetail',
            name='title',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Article', to_field='title', verbose_name='文章标题'),
        ),
    ]
