# Generated by Django 2.2.3 on 2019-08-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20190812_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetail',
            name='title',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleDetail',
        ),
    ]
